const cars = [
    {
        'id': 1,
        'userId': 1,
        'images': ["/audi_r8.png", "/audi_r8_2.jpg", "/audi_r8_3.jpg"],
        'mark': "Audi",
        'model': "R8",
        'title': "Audi R8",
        'price': "6.000.000",
        'mileage': "10.000",
        'year': "2016",
        'ownersCount': "2",
        'gearbox': "Роботизированная",
        'color': "Серый",
        'engine': '550 л.с., 5.2 л, Бензин',
        'driveShaft': 'Полный',
        'status': 'active'
    },
    {
        'id': 2,
        'userId': 1,
        'images': ["/bmw_m4.png", "/bmw_m4_2.jpg"],
        'mark': "Bmw",
        'model': "M4",
        'title': "Bmw M4",
        'price': "4.000.000",
        'mileage': "50.000",
        'year': "2018",
        'ownersCount': "2",
        'gearbox': "Роботизированная",
        'color': 'Белый',
        'engine': '3.0 л, 450 л.с., Бензин',
        'driveShaft': 'Задний',
        'status': 'active'
    },
    {
        'id': 3,
        'userId': 1,
        'images': ["/toyota_rav4.png"],
        'mark': "Toyota",
        'model': "Rav4",
        'title': "Toyota Rav4",
        'price': "10.000.000",
        'mileage': "30.000",
        'year': "2025",
        'ownersCount': "1",
        'gearbox': "Вариатор",
        'color': "Металлик",
        'engine': "2.0 л, 171 л.с., Бензин",
        'driveShaft': "Полный",
        'status': 'active'
    },
    {
        'id': 4,
        'userId': 4,
        'images': ["/mclaren_720s.png"],
        'mark': "Mclaren",
        'model': "720s",
        'title': "Mclaren 720s",
        'price': "20.000.000",
        'mileage': "1.000",
        'year': "2018",
        'ownersCount': "1",
        'gearbox': "Роботизированная",
        'color': "Белый",
        'engine': "4.0 л, 720 л.с., Бензин",
        'driveShaft': "Задний",
        'status': 'active'
    },
    {
        'id': 5,
        'userId': 5,
        'images': ["/porsche_panamera.png"],
        'mark': "Porsche",
        'model': "Panamera",
        'title': "Porsche Panamera",
        'price': "10.000.000",
        'mileage': "45.000",
        'year': "2021",
        'ownersCount': "1",
        'gearbox': "Роботизированная",
        'color': "Черный",
        'engine': "2.9 л, 330 л.с., Бензин",
        'driveShaft': "Полный",
        'status': 'active'
    },
    {
        'id': 6,
        'userId': 6,
        'images': ["/vaz_2107.png"],
        'mark': "Lada (Ваз)",
        'model': "2107",
        'title': "Lada (Ваз) 2107",
        'price': "100.000",
        'mileage': "200.000",
        'year': "2006",
        'ownersCount': "3",
        'gearbox': "Механическая",
        'color': "Белый",
        'engine': "1.5 л, 72 л.с., Бензин",
        'driveShaft': "Задний",
        'status': 'active'
    },
    {
        'id': 7,
        'userId': 7,
        'images': ["/nissan_skyline.png"],
        'mark': "Nissan",
        'model': "Skyline R34",
        'title': "Nissan Skyline R34",
        'price': "1.500.000",
        'mileage': "131.000",
        'year': "1998",
        'ownersCount': "2",
        'gearbox': "Автоматическая",
        'color': "Черный",
        'engine': "2.5 л, 200 л.с., Бензин",
        'driveShaft': "Задний",
        'status': 'active'
    },
    {
        'id': 8,
        'userId': 8,
        'images': ["/audi_r8_2.jpg", "/audi_r8_3.jpg"],
        'mark': "Audi",
        'model': "R8",
        'title': "Audi R8",
        'price': "6.000.000",
        'mileage': "10.000",
        'year': "2016",
        'ownersCount': "2",
        'gearbox': "Роботизированная",
        'color': "Серый",
        'engine': '550 л.с., 5.2 л, Бензин',
        'driveShaft': 'Полный',
        'status': 'active'
    },
];